### ISSUE TITLE
Monorepos support and decoupling packages

### ISSUE THREAD

**Issue by aogaili** [leonardoventurini/helene#11]
The client SDK, React hooks and Server are all exported under one package yet they could be split into smaller npm packages since they could be used independently. 

Something like:
- @helene/client
- @helene/server
- @helene/reactjs

Could also have plug-ins repo for auth, etc.  Monorepo could be managed by workspaces using BunJS or PNPM for performance.

**Comment by leonardoventurini** [comment]
Sadly the org `@helene` was already taken but I could create `@helenejs`.

**Comment by leonardoventurini** [comment]
Started the split here #13, do you think it would be a problem if we kept the core client and server in the same package? It has different entry points for browser and node + isomorphic ws.

**Comment by leonardoventurini** [comment]
On better thought perhaps Meteor or some other framework might not use those separate entry points. I will keep it as core for now until I get the other packages decoupled then I can focus on decoupling client/server.

**Comment by leonardoventurini** [comment]
Hey @aogaili the separation is complete, can you review the PR please? #13
